version: '3.9'

services:
  redis:
      image: redis:alpine

  web:
    build: .
    command: bash -c "arq tasks.WorkerSettings & gunicorn main:app -b :8080 --worker-class aiohttp.GunicornWebWorker --reload --access-logfile -"
    ports:
      - 8080:8080
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CPA_MONKEY_DENY=BUILD_TRACER